### ISSUE TITLE
Teleporters to Faust Messed up Camera

### ISSUE THREAD

**Issue by RedDragoon101** [Legend-of-Dragoon-Modding/Severed-Chains#1314] opened 2024-05-21 20:57 UTC
Going through this teleporter...
![Screenshot (429)](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70169883/79228be6-acc3-45f9-bf0e-6c3d84b5fc05)

**Comment by RedDragoon101** [comment] 2024-05-21 20:57
Leads to this screen, where the camera doesnt scroll down
![Screenshot (428)](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70169883/94f8513e-ab62-48a7-bfdf-bcc1abeaf5ae)

**Comment by avionanx** [comment] 2024-05-22 10:36
duplicate of #1132 closed by 8188913

**Closed by avionanx** 2024-05-22 10:36 UTC
