### ISSUE TITLE
Guards in Twin Castle stairs will flicker when "off screen" in widescreen mode

### ISSUE THREAD

**Issue by elementallight** [Legend-of-Dragoon-Modding/Severed-Chains#1794] opened 2024-11-10 09:38 UTC
https://github.com/user-attachments/assets/fe21d65c-e7a0-4c5a-94e5-3ee83720d49c

Guard on left was flickering when first entering room and changed to the right guard when on stair case. when in standard 4:3 these models are off screen.

**Comment by theflyingzamboni** [comment] 2024-11-15 17:40
This will take some fairly substantial script modification to fix. The issue is that each guard pair is actually one single NPC that gets moved to whichever side is on screen, so when widescreen is enabled they jump back and forth.

**Comment by LordMonoxide** [comment] 2024-11-24 02:47
@avionanx is this feasible? Would be nice to have since widescreen will be in RB3

**Comment by LordMonoxide** [comment] 2024-12-21 14:52
Turns out it is two NPCs but they hide the one that's supposed to be off screen ¯\_(ツ)_/¯ should be a pretty easy fix to just... not

**Closed** 2024-12-28 14:33 UTC
Labels: script engine
