### ISSUE TITLE
Screw Shell attack going way beyond player

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Severed-Chains#1375] opened 2024-05-28 02:14 UTC
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/132630165/2ada2cb7-0b39-42e5-802c-b9ef21c485db

**Comment by theflyingzamboni** [comment] 2024-05-29 20:15
Duplicate of #707

**Closed by theflyingzamboni** 2024-05-29 20:15 UTC
