### ISSUE TITLE
Issue still persists with Rose's Dark Dragon (white streak still not rendering)

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1799] opened 2024-11-16 22:18 UTC
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/issues/1566

Expected result:

![expected result](https://github.com/user-attachments/assets/7bd0602d-4c2b-4578-8879-42e91e01b05e)

Current result:

![current result](https://github.com/user-attachments/assets/85b3995f-8bed-4c24-ab11-3bd07e6175e2)

Tested on commit: https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/ff9bace10a27253abc2f1e1150ecdf5bcedf7657

**Comment by theflyingzamboni** [comment] 2024-11-17 22:47
Duplicate of #1567

**Closed by theflyingzamboni** 2024-11-17 22:47 UTC
