### ISSUE TITLE
Equip Swap Screen Crash

### ISSUE THREAD

**Issue by avionanx** [Legend-of-Dragoon-Modding/Severed-Chains#1774] opened 2024-10-23 17:05 UTC
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 9
	at legend.game.SItem.canEquip(SItem.java:786)
	at legend.game.inventory.screens.EquipmentScreen.getEquippableItemsForCharacter(EquipmentScreen.java:130)
	at legend.game.inventory.screens.EquipmentScreen.render(EquipmentScreen.java:81)
	at legend.game.inventory.screens.MenuScreen.renderScreen(MenuScreen.java:68)
	at legend.game.inventory.screens.MenuStack.propagate(MenuStack.java:125)
	at legend.game.inventory.screens.MenuStack.render(MenuStack.java:97)
	at legend.game.SItem.renderMenus(SItem.java:613)
	at legend.game.Scus94491BpeSegment_8002.loadAndRenderMenus(Scus94491BpeSegment_8002.java:899)
	at legend.game.submap.SMap.tick(SMap.java:3849)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:416)
	at legend.core.RenderEngine.lambda$init$17(RenderEngine.java:504)
	at legend.core.opengl.Window$Events.onDraw(Window.java:697)
	at legend.core.opengl.Window.tickFrame(Window.java:337)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:314)
	at legend.core.RenderEngine.run(RenderEngine.java:1131)
	at legend.core.GameEngine.start(GameEngine.java:251)
	at legend.game.Main.main(Main.java:24)
```

**Comment by LordMonoxide** [comment] 2024-12-06 02:29
Closed wrong ticket

**Comment by LordMonoxide** [comment] 2024-12-06 02:34
I'm trying to reproduce this and it looks like it shouldn't be possible unless you had zero characters. Got any more context?

**Comment by avionanx** [comment] 2024-12-11 17:59
This happened during lohan issue where every character got removed from party

**Comment by warblgarbl** [comment] 2024-12-16 03:39
Probably a consequence of how Dart was losing his 0x23 flag with unlock party **disabled**?

**Comment by LordMonoxide** [comment] 2024-12-21 02:35
Can't reproduce, closing

**Closed by LordMonoxide** 2024-12-21 02:35 UTC
