### ISSUE TITLE
Patrol Guards Are Not Spawning (Warp ID: 24,25,26)

### ISSUE THREAD

**Issue by Ehko4** [Legend-of-Dragoon-Modding/Severed-Chains#1703] opened 2024-05-29 12:46 UTC
**Describe the bug**
After dialog with the Lavitz and Dart, the guards that patrol these Submaps do not spawn. 

**To Reproduce**
1. Go to Submaps Warp IDs 24, 25, and/or 26
2. N/A
3. N/A
4. Hang out to see error

**Expected behavior**
A guard should spawn to patrol at any entrance to the Submaps 24 and 26. For Submap 25, guards should spawn at the main entrance or either of the two main walkway entrances, not the bottom two. 

Edit - Leaving via the main entrance and coming back in causes the guards to start spawning.

**Comment by LordMonoxide** [comment] 2024-12-11 22:56
Got a couple players reporting this may be caused by save anywhere

**Comment by LordMonoxide** [comment] 2024-12-16 16:18
Closed by #1855

**Closed by LordMonoxide** 2024-12-16 16:18 UTC
